#!/bin/bash

# Script to help get Firebase web app configuration

PROJECT_ID="studio-5771582587-5ae19"
FIREBASE_CONSOLE_URL="https://console.firebase.google.com/project/${PROJECT_ID}/settings/general"

echo "🔧 Firebase Web App Configuration Setup"
echo "======================================="
echo ""
echo "Project ID: ${PROJECT_ID}"
echo ""
echo "To get your Firebase web app configuration:"
echo ""
echo "1. Open this URL in your browser:"
echo "   ${FIREBASE_CONSOLE_URL}"
echo ""
echo "2. Scroll down to 'Your apps' section"
echo ""
echo "3. If you don't have a web app yet:"
echo "   - Click the Web icon (</>)"
echo "   - Register your app with a nickname (e.g., 'Agentic Appointment App')"
echo "   - Click 'Register app'"
echo ""
echo "4. Copy the configuration values:"
echo "   - apiKey"
echo "   - authDomain (usually: ${PROJECT_ID}.firebaseapp.com)"
echo "   - projectId (should be: ${PROJECT_ID})"
echo "   - appId"
echo ""
echo "5. Add them to your .env file:"
echo "   VITE_FIREBASE_API_KEY=<your-api-key>"
echo "   VITE_FIREBASE_AUTH_DOMAIN=${PROJECT_ID}.firebaseapp.com"
echo "   VITE_FIREBASE_PROJECT_ID=${PROJECT_ID}"
echo "   VITE_FIREBASE_APP_ID=<your-app-id>"
echo ""
echo "Or run: node setup-firebase-web-env.js"
echo ""

